// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbzfhuaofkdndgwlvagv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiemZodWFvZmtkbmRnd2x2YWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjM5MTMsImV4cCI6MjA2MzIzOTkxM30.KIiABuxLuvKRF46njW7lLC9Ee7hzUJi-9A2-14LSIw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);